const fishImageMap: Record<string, any> = {
  "../assets/images/fish/black_sea_bream.png": require("../../assets/images/fish/black_sea_bream.png"),
  "../assets/images/fish/cod.png": require("../../assets/images/fish/cod.png"),
  "../assets/images/fish/crab.png": require("../../assets/images/fish/crab.png"),
  "../assets/images/fish/cutlassfish.png": require("../../assets/images/fish/cutlassfish.png"),
  "../assets/images/fish/filefish.png": require("../../assets/images/fish/filefish.png"),
  "../assets/images/fish/olive_flounder.png": require("../../assets/images/fish/olive_flounder.png"),
  "../assets/images/fish/korean_rockfish.png": require("../../assets/images/fish/korean_rockfish.png"),
  "../assets/images/fish/mackerel.png": require("../../assets/images/fish/mackerel.png"),
  "../assets/images/fish/marbled_sole.png": require("../../assets/images/fish/marbled_sole.png"),
  "../assets/images/fish/octopus.png": require("../../assets/images/fish/octopus.png"),
  "../assets/images/fish/striped_beakfish.png": require("../../assets/images/fish/striped_beakfish.png"),
  "../assets/images/fish/red_sea_bream.png": require("../../assets/images/fish/red_sea_bream.png"),
  "../assets/images/fish/baby_octopus.png": require("../../assets/images/fish/baby_octopus.png"),
  "../assets/images/fish/snow_crab.png": require("../../assets/images/fish/snow_crab.png"),
  "../assets/images/fish/squid.png": require("../../assets/images/fish/squid.png"),
  "../assets/images/fish/tilefish.png": require("../../assets/images/fish/tilefish.png"),
  "../assets/images/fish/webfoot_octopus.png": require("../../assets/images/fish/webfoot_octopus.png"),
  "../assets/images/fish/largescale_blackfish.png": require("../../assets/images/fish/largescale_blackfish.png"),
  "../assets/images/fish/bigfin_reef_squid.png": require("../../assets/images/fish/bigfin_reef_squid.png"),
  "../assets/images/fish/scorpionfish.png": require("../../assets/images/fish/scorpionfish.png"),
  "../assets/images/fish/marbled_rockfish.png": require("../../assets/images/fish/marbled_rockfish.png"),
  "../assets/images/fish/japanese_jack_mackerel.png": require("../../assets/images/fish/japanese_jack_mackerel.png"),
  "../assets/images/fish/japanese_amberjack.png": require("../../assets/images/fish/japanese_amberjack.png"),
  "../assets/images/fish/japanese_seabass.png": require("../../assets/images/fish/japanese_seabass.png"),
};

export default fishImageMap