const imageMap: { [filename: string]: any } = {
  "black_sea_bream.png": require("../assets/images/fish/black_sea_bream.png"),
  "cod.png": require("../assets/images/fish/cod.png"),
  "crab.png": require("../assets/images/fish/crab.png"),
  "cutlassfish.png": require("../assets/images/fish/cutlassfish.png"),
  "filefish.png": require("../assets/images/fish/filefish.png"),
  "olive_flounder.png": require("../assets/images/fish/olive_flounder.png"),
  "korean_rockfish.png": require("../assets/images/fish/korean_rockfish.png"),
  "mackerel.png": require("../assets/images/fish/mackerel.png"),
  "marbled_sole.png": require("../assets/images/fish/marbled_sole.png"),
  "octopus.png": require("../assets/images/fish/octopus.png"),
  "striped_beakfish.png": require("../assets/images/fish/striped_beakfish.png"),
  "red_sea_bream.png": require("../assets/images/fish/red_sea_bream.png"),
  "baby_octopus.png": require("../assets/images/fish/baby_octopus.png"),
  "snow_crab.png": require("../assets/images/fish/snow_crab.png"),
  "squid.png": require("../assets/images/fish/squid.png"),
  "tilefish.png": require("../assets/images/fish/tilefish.png"),
  "webfoot_octopus.png": require("../assets/images/fish/webfoot_octopus.png"),
  "largescale_blackfish.png": require("../assets/images/fish/largescale_blackfish.png"),
  "bigfin_reef_squid.png": require("../assets/images/fish/bigfin_reef_squid.png"),
  "scorpionfish.png": require("../assets/images/fish/scorpionfish.png"),
  "marbled_rockfish.png": require("../assets/images/fish/marbled_rockfish.png"),
  "japanese_jack_mackerel.png": require("../assets/images/fish/japanese_jack_mackerel.png"),
  "japanese_amberjack.png": require("../assets/images/fish/japanese_amberjack.png"),
  "japanese_seabass.png": require("../assets/images/fish/japanese_seabass.png"),
};

export default imageMap;
