spring:
  application:
    name:
      BE
  config:
    import:
      optional:file:.env[.properties]
  jwt:
    secret: OnetwothreeDroptheBeat134vasndjnaiosuervoiuasoeruvnasopieurvanpsoierunaspoieruvnaposieurn
  security:
     oauth2:
       client:
         registration:
           kakao:
             client-name: kakao
             client-id: 4df41bec6f36ccdec491270265b88e43
#             client-secret:
             redirect-uri: http://localhost:8080/oauth/callback
             client-authentication-method:
             scope: name,email
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL} # 이거 로컬 DB임
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      pool-name: hikari
      maximum-pool-size: 1000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${JPA_DDL=validate}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true #자잘한 경고 뜨는 거 때문에 설정 명시
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
logging.level:
  org.hibernate.SQL: debug

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /v3/api-docs/swagger-ui # html 문서 접속 경로
    #    disable-swagger-default-url: true
    #    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    /**