#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd "$(git rev-parse --show-toplevel)/FE/frontend"

STAGED_FILES=$(git diff --name-only --cached --relative | grep -E '\.(js|jsx|ts|tsx)$')

if [ -n "$STAGED_FILES" ]; then
  echo "🔍 Linting & Formatting staged files..."

  echo "$STAGED_FILES" | xargs yarn eslint --fix

  echo "$STAGED_FILES" | xargs yarn prettier --write

  echo "$STAGED_FILES" | xargs git add
else
  echo "✅ No relevant staged files to lint or format."
fi
